sudo: false
dist: trusty
language: python
python:
  - 2.6
  - 2.7
  - 3.6
  - 3.7-dev
services:
  - docker

install:
  - pip install tox tox-travis molecule docker

script:
  - tox
  - molecule --version
  - ansible --version
  - molecule lint
  - molecule syntax
  - molecule test
